AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  birdnetanalyzerlambdafunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 3008
      Timeout: 900
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 10240
      Environment:
        Variables:
          DDB_TABLE: BirdTagMedia
          LOCAL_TEST: '0'
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: >-
        591256669981.dkr.ecr.ap-southeast-2.amazonaws.com/birdnetanalyzer-lambdaimage@sha256:a5f65066b52c450793186fa87ba1c8011287d210dc6ae0160d8eea319d63a9ac
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !GetAtt Bucket1.Arn
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !GetAtt Bucket1.Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - >-
                  arn:aws:dynamodb:ap-southeast-2:591256669981:table/BirdTagMedia
                - >-
                  arn:aws:dynamodb:ap-southeast-2:591256669981:table/BirdTagMedia/index/*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: >-
                arn:aws:logs:ap-southeast-2:591256669981:log-group:/aws/lambda/birdnet-analyzer:*
            - Effect: Allow
              Action:
                - xray:PutTraceSegments
                - xray:PutTelemetryRecords
              Resource: '*'
            - Effect: Allow
              Action:
                - ecr:GetDownloadUrlForLayer
                - ecr:BatchGetImage
                - ecr:BatchCheckLayerAvailability
              Resource: >-
                arn:aws:ecr:ap-southeast-2:591256669981:repository/birdnet-analyzer
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-southeast-2:591256669981:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-southeast-2:591256669981:log-group:/aws/lambda/birdnetanalyzer-lambdafunction:*
      SnapStart:
        ApplyOn: None
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: upload/audio
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  BucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: Bucket1
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Deny
            Principal: '*'
            Resource:
              - arn:aws:s3:::Bucket1/*
              - arn:aws:s3:::Bucket1
            Condition:
              Bool:
                aws:SecureTransport: false
